In [25]:
import torchvision
import torch

In [26]:
train = torchvision.datasets.MNIST("./data", download=True, train=True, transform=torchvision.transforms.ToTensor())
test = torchvision.datasets.MNIST("./data", download=True, train=False, transform=torchvision.transforms.ToTensor())
train, test

(Dataset MNIST
     Number of datapoints: 60000
     Root location: ./data
     Split: Train
     StandardTransform
 Transform: ToTensor(),
 Dataset MNIST
     Number of datapoints: 10000
     Root location: ./data
     Split: Test
     StandardTransform
 Transform: ToTensor())

In [27]:
train.data, train.data.shape

(tensor([[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         ...,
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0

In [28]:
train.train_labels, test.test_labels

/mnt/ssd1/ResearchPortfolio/PaperFromScratchSeries/VAE/.venv/lib/python3.14/site-packages/torchvision/datasets/mnist.py:66: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/mnt/ssd1/ResearchPortfolio/PaperFromScratchSeries/VAE/.venv/lib/python3.14/site-packages/torchvision/datasets/mnist.py:71: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


(tensor([5, 0, 4,  ..., 5, 6, 8]), tensor([7, 2, 1,  ..., 4, 5, 6]))

In [29]:
for a, b in train:
    print(a, b)
    print(type(a), type(b))
    break

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

# 2. Data Loader

In [30]:
from torch.utils.data import DataLoader

train_dataset = DataLoader(train, batch_size=128, shuffle=True)
test_dataset = DataLoader(test, batch_size=128, shuffle=False)
train_dataset, test_dataset

(<torch.utils.data.dataloader.DataLoader at 0x74d0f1b9a0d0>,
 <torch.utils.data.dataloader.DataLoader at 0x74d0f1b7f5c0>)

In [31]:
type(train_dataset.dataset.data)

torch.Tensor

In [32]:
next(iter(train_dataset))[0].shape, next(iter(train_dataset))[1].shape

(torch.Size([128, 1, 28, 28]), torch.Size([128]))

In [33]:
# 

# 3. VAE from Scratch

In [34]:
trainData = train.data.reshape(train.data.shape[0], -1)
trainData = (trainData != 0) * 1.0

In [35]:
trainData[0]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 0., 0., 0., 0., 

In [36]:
# latent-dimension
J = 2

In [68]:
import torch.nn as nn

# TODO
# 1. Add activation

class Encoder(nn.Module):
    def __init__(self, J):
        super(Encoder, self).__init__()

        self.w1 = nn.Parameter(torch.randn(500, 784))
        self.b1 = nn.Parameter(torch.randn(500))

        self.w2 = nn.Parameter(torch.randn(2*J, 500))
        self.b2 = nn.Parameter(torch.randn(2*J))

    def forward(self, x):
        self.out = self.w1 @ x + self.b1
        self.out = self.w2 @ self.out + self.b2
        return self.out

class Reparametrizer(nn.Module):
    # R^(2J) -> R^J
    def __init__(self, J):
        super(Reparametrizer, self).__init__()

        # Not Learnable, just pure randomness
        self.epsilon = torch.randn(J)

    def forward(self, x):
        self.out = x[:J] + x[J:] * self.epsilon
        return self.out


class Decoder(nn.Module):
    def __init__(self, J):
        super(Decoder, self).__init__()

        self.w1 = nn.Parameter(torch.randn(500, 2))
        self.b1 = nn.Parameter(torch.randn(500))

        self.w2 = nn.Parameter(torch.randn(784, 500))
        self.b2 = nn.Parameter(torch.randn(784))

    def forward(self, x):
        self.out = self.w1 @ x + self.b1
        self.out = self.w2 @ self.out + self.b2
        return self.out



In [69]:
train.data[0].flatten().shape

torch.Size([784])

In [75]:
torch.manual_seed(42)

e = Encoder(J)
x = trainData[0]
encodedX = e(x)
encodedX

tensor([566.4133, 524.0556,  13.2978, 103.2326], grad_fn=<AddBackward0>)

In [76]:
r = Reparametrizer(J)
reX = r(encodedX)
reX

tensor([573.1008, 310.4732], grad_fn=<AddBackward0>)

In [77]:
d = Decoder(J)
decodedX = d(reX)
decodedX

tensor([ 3.8981e+03,  2.1379e+04, -3.2654e+03, -1.1013e+04, -5.7771e+03,
         4.8841e+03,  2.0081e+04,  1.9357e+04,  1.5476e+04, -7.6143e+03,
        -1.4318e+04, -4.2579e+03, -2.1803e+03, -2.0183e+03,  1.0873e+04,
        -1.1687e+04, -3.0561e+04, -1.5022e+04, -1.3329e+04,  7.9797e+02,
        -9.6784e+03, -7.6819e+03, -1.9749e+03,  1.7233e+04, -9.1791e+03,
        -2.2877e+04,  2.1282e+04,  1.1014e+04, -6.3904e+03, -3.5350e+03,
         7.3400e+03, -9.5635e+03, -9.7005e+03,  4.1631e+03, -2.8159e+03,
        -2.5462e+04,  8.4499e+03,  1.2991e+04, -3.6918e+04, -6.1699e+03,
        -6.7085e+03, -2.9961e+04, -1.8347e+04, -1.4018e+04,  9.2031e+01,
         3.1321e+04,  5.0456e+03, -1.8186e+04,  3.0814e+04,  6.6514e+03,
        -3.3096e+03, -4.2051e+03,  1.6549e+04, -1.3574e+04,  2.8478e+04,
        -2.5096e+04,  2.1843e+04,  2.4310e+04,  1.5699e+04,  1.1748e+04,
         1.8962e+04,  1.1202e+04, -8.7864e+03,  9.3876e+03,  3.0731e+03,
         1.0174e+04,  1.3198e+04,  2.2679e+04,  1.1